lane :build do
build_app(
  workspace: "ClashX.xcworkspace",
  scheme: "ClashX",
  export_method: "developer-id",
  skip_package_pkg: "true"
)
end

lane :beta do
current_version = get_version_number(
  target: "ClashX"
)
timestamp = Time.now.utc
new_build_identifier = "%d%02d%02d%02d%02d" % [
    timestamp.year,
    timestamp.month,
    timestamp.day,
    timestamp.hour,
    timestamp.min,
]
new_version = current_version + "." + new_build_identifier
increment_build_number_in_plist(
    build_number: new_version,
    target: 'ClashX'
)
end